config/routes.rb
Rails.application.routes.draw do
  # get ':fix', to: 'translated_stories#fix', as: :translated_story

  # For attachments: https://stackoverflow.com/questions/49515529/rails-5-2-active-storage-purging-deleting-attachments
  # WIP
  resources :attachments do
    member do
      get :destroy
      delete :destroy
      delete :regenerate
      delete :destroy_all
      delete :regenerate_all
    end
  end

  resources :translated_stories do
    # needs collections or wont have DFLT CRUD
    # collection do
    # #   # get :fix_translated_story
    #   post :fix_translated_story
    # end
    member do
      # from 2.10.1 https://guides.rubyonrails.org/routing.html#creating-paths-and-urls-from-objects
      get 'fix'
    end
  end
  devise_for :users
  resources :story_templates
  resources :story_paragraphs do
    member do
      get 'gen_audio'
    end
  end
  get 'pages/index'
  get 'pages/about'
  get 'pages/help'

  # AI functionality
  get 'pages/slow_function'
  post 'pages/slow_function'
  get 'pages/ai_test'
  post 'pages/ai_test'

  resources :stories
  resources :kids
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  #  match '//' # => StoryRebuiltControler
  get '/story_rebuilt/:id', to: 'stories#show_rebuilt', as: 'story_rebuilt'

  match '/delayed_job' => DelayedJobWeb, :anchor => false, :via => %i[get post]

  # fix_translated_story_path
  # get '/fix_translated_story', 'translated_story#fix_translated_story', as: :fix_translated_story

  # Defines the root path route ("/")
  root 'pages#index'
end

app/models/story_template.rb
# create_table "story_templates", force: :cascade do |t|
#     t.string "short_code"
#     t.string "description"
#     t.text "template"
#     t.text "internal_notes"
#     t.integer "user_id"
# end

class StoryTemplate < ApplicationRecord
    include TemplateSubstitutable

    validates :short_code, uniqueness: true,  presence: true # short index
    validates :description, uniqueness: true,  presence: true # long index
    validates :short_code, presence: true,
        format: { with: /\A([a-z_-]+)\z/, message: 'No spaces, just dash underscores and lower cases' }


    #kid_description = opts.fetch :kid_description, 'A blue-eyed afroamerican 6-year-old red-haired girl called Foobar Baz' # if kid_description.nil?
      #character = opts.fetch :character, pickARandomElementOf(CHARACTERS) #   if character.nil?
      #setting = opts.fetch :setting, pickARandomElementOf(SETTINGS) #  if setting.nil?
      #plot = opts.fetch :plot, pickARandomElementOf(PLOTS) #  if plot.nil?


        def instanciate
            ' TODO(ricc): the idea is to take the template and apply random or deterministic functions to the {parts}...'
            instanciated_template = self.template
            parts2bChanged = instanciated_template.scan(/{{[a-z]+}}/)
            parts2bChanged.each do |x|
                instanciated_template = substitute_var(x, instanciated_template)
#                case my_var
#                    when 'character': instanciated_template =
            end

            "👢 instanciate(WIP): #{yellow instanciated_template}"
        end

        def to_s
            "STmpl(#{id}): '#{short_code}' #{validity_emoji}.."
        end

        def self.emoji
            '📋'
        end


    end

app/controllers/story_templates_controller.rb
class StoryTemplatesController < ApplicationController
  before_action :set_story_template, only: %i[ show edit update destroy ]

  # GET /story_templates or /story_templates.json
  def index
    @story_templates = StoryTemplate.all
  end

  # GET /story_templates/1 or /story_templates/1.json
  def show
  end

  # GET /story_templates/new
  def new
    @story_template = StoryTemplate.new
  end

  # GET /story_templates/1/edit
  def edit
  end

  # POST /story_templates or /story_templates.json
  def create
    @story_template = StoryTemplate.new(story_template_params)

    respond_to do |format|
      if @story_template.save
        format.html { redirect_to story_template_url(@story_template), notice: "Story template was successfully created." }
        format.json { render :show, status: :created, location: @story_template }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /story_templates/1 or /story_templates/1.json
  def update
    respond_to do |format|
      if @story_template.update(story_template_params)
        format.html { redirect_to story_template_url(@story_template), notice: "Story template was successfully updated." }
        format.json { render :show, status: :ok, location: @story_template }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /story_templates/1 or /story_templates/1.json
  def destroy
    @story_template.destroy

    respond_to do |format|
      format.html { redirect_to story_templates_url, notice: "Story template was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story_template
      @story_template = StoryTemplate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_template_params
      params.require(:story_template).permit(:short_code, :description, :template, :internal_notes, :user_id)
    end
end

app/helpers/story_templates_helper.rb
module StoryTemplatesHelper

  def render_colored_story_template_template(story_template)
    #.bg-warning
    #        <%= raw( p.translated_text.gsub(/\*\*(A.* [1-5])\*\*/) { "<span class='act15' ><b><u>#{Regexp.last_match(1)}</u></b></span><br/><br/>" }.gsub('**','') )%>

    return content_tag :tt, story_template.template.gsub(/{{(\w+)}}/) {
      "<span class='act15 bg-warning' ><b>{{#{Regexp.last_match(1)}}}</b></span>"
    }.gsub("\n", "<br/>\n").html_safe
    #'sobenme')
    #"AAA #{story_template.template}"
  end

end

app/views/story_templates/_form.html.erb
<%= form_with(model: story_template, multipart: true) do |form| %>
  <% if story_template.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(story_template.errors.count, "error") %> prohibited this story_template from being saved:</h2>

      <ul>
        <% story_template.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :short_code, style: "display: block" %>
    <%= form.text_field :short_code %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :template, style: "display: block" %>
    <%= form.text_area :template %>
  </div>

  <div>
    <%= form.label :internal_notes, style: "display: block" %>
    <%= form.text_area :internal_notes %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/story_templates/_story_template.html.erb
<div id="<%= dom_id story_template %>">
  <h2>
    <%= StoryTemplate.emoji %>
    <%= link_to story_template.short_code,story_template %>
  </h2>

  <p>

    <strong>Description:</strong>
    <%= story_template.description %>
  </p>
  <p>
    <strong>Template:</strong>
    <%= render_colored_story_template_template(story_template) %>
  </p>

<!--


  <p>
    <strong>Internal notes:</strong>
    <%#= story_template.internal_notes %>
  </p>

  <p>
    <strong>User:</strong>
    <%#= link_to( story_template.user,story_template.user) if story_template.user %>
  </p>
-->
</div>

app/views/story_templates/edit.html.erb
<h1>Editing story template</h1>

<%= render "form", story_template: @story_template %>

<br>

<div>
  <%= link_to "Show this story template", @story_template %> |
  <%= link_to "Back to story templates", story_templates_path %>
</div>

app/views/story_templates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Story templates</h1>

<div id="story_templates">
  <% @story_templates.each do |story_template| %>
    <%#= render partial: story_template, locals: {short: true }, short: 'index'  %>
      <%#= link_to "Show this story template", story_template %>
      <div id="<%= dom_id story_template %>">
    <p>
      👀<tt><%= link_to story_template.short_code,story_template %></tt>
      (<i><%= story_template.description %></i>)
    </p>
  </div>

  <% end %>
</div>

<%= link_to "➕ New story template", new_story_template_path %>

app/views/story_templates/new.html.erb
<h1>New story template</h1>

<%= render "form", story_template: @story_template %>

<br>

<div>
  <%= link_to "Back to story templates", story_templates_path %>
</div>

app/views/story_templates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @story_template %>

<div>
  <%= link_to "Edit this story template", edit_story_template_path(@story_template) %> |
  <%= link_to "Back to story templates", story_templates_path %>

  <%= button_to "Destroy this story template", @story_template, method: :delete %>
</div>