config/routes.rb
Rails.application.routes.draw do
  # get ':fix', to: 'translated_stories#fix', as: :translated_story

  # For attachments: https://stackoverflow.com/questions/49515529/rails-5-2-active-storage-purging-deleting-attachments
  # WIP
  resources :attachments do
    member do
      get :destroy
      delete :destroy
      delete :regenerate
      delete :destroy_all
      delete :regenerate_all
    end
  end

  resources :translated_stories do
    # needs collections or wont have DFLT CRUD
    # collection do
    # #   # get :fix_translated_story
    #   post :fix_translated_story
    # end
    member do
      # from 2.10.1 https://guides.rubyonrails.org/routing.html#creating-paths-and-urls-from-objects
      get 'fix'
    end
  end
  devise_for :users
  resources :story_templates
  resources :story_paragraphs do
    member do
      get 'gen_audio'
    end
  end
  get 'pages/index'
  get 'pages/about'
  get 'pages/help'

  # AI functionality
  get 'pages/slow_function'
  post 'pages/slow_function'
  get 'pages/ai_test'
  post 'pages/ai_test'

  resources :stories
  resources :kids
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  #  match '//' # => StoryRebuiltControler
  get '/story_rebuilt/:id', to: 'stories#show_rebuilt', as: 'story_rebuilt'

  match '/delayed_job' => DelayedJobWeb, :anchor => false, :via => %i[get post]

  # fix_translated_story_path
  # get '/fix_translated_story', 'translated_story#fix_translated_story', as: :fix_translated_story

  # Defines the root path route ("/")
  root 'pages#index'
end

app/models/story_paragraph.rb
# A story is composed of N paragraphs

# # MODEL
# StoryParagraph(id: integer,
#    story_index: integer,
#    original_text: text,
#    genai_input_for_image: text,
#    internal_notes: text,
#    translated_text: text,
#    language: string,
#    story_id: integer,
#    rating: integer,
#    created_at: datetime,
#    updated_at: datetime)
#
# # POLYMORPHIC
# p_images (many)  Example which works: s.p_image1.attach(io: File.open('whiskers.png'), filename: :whiskers)
# p_image1 (one)
# p_image2 (one)
# p_image3 (one)
# p_image4 (one)
class StoryParagraph < ApplicationRecord
  include AiImageable
  # OLD
  belongs_to :story
  # NEW
  belongs_to :translated_story

  validates :story_index, uniqueness: { scope: %i[language story_id] }
  validates :story_index, numericality: { in: 1..1000 }
  validates :rating, numericality: { in: 1..5 }, allow_nil: true
  validates :language, presence: true,
                       format: { with: AVAIL_LANGUAGE_REGEX,
                                 message: 'We only support ITalian, Spanish, portuguese, german, english, Russian and Japanese now. Ok now also 🇫🇷 :)' }

  # image attachments. Not sure whether to force 4 or ahev any. 4 would be easy for frontend (square with 4)
  has_many_attached :p_images # , service: :google

  has_one_attached :p_image1 # , service: :google
  has_one_attached :p_image2 # , service: :google
  has_one_attached :p_image3 # , service: :google
  has_one_attached :p_image4 # , service: :google

  has_one_attached :mp3_audio # created with text2speech API!

  # PROD
  after_create :after_creation_magic
  # DEV: easier to debug
  # after_save :after_creation_magic
  # after_save :after_creation_delayed_magic

  ## MAGIC thing
  def attach(_filename)
    attach!(_filename) unless p_image1.attached?
  end

  def attach!(_filename)
    # p_image1.attach(io: File.open(File.expand_path(_filename)), filename: _filename)
    attach_file_to_attachable_field(p_image1, _filename)
  end

  def attached?
    puts 'DEPRECATED. Stop using this now that you also attach audios!'
    p_image1.attached?
  end
  def image_attached?
    p_image1.attached?
  end
  def audio_attached?
    mp3_audio.attached?
  end

  def after_creation_delayed_magic
    delay(queue: 'story_paragrah::after_creation_magic').after_creation_magic
  end

  def after_creation_magic
    puts '1 [DELAYED] if translation is nil but we have original text AND language => trigger GTranslate (DELAY)'
    write_translated_content_for_paragraph if translated_text.to_s.length < 5
    puts '2 [NOW] if picture text not available -> generate it determiniistically (now)'
    generate_genai_text_for_paragraph if genai_input_for_image.to_s.length < 10 # genai_input_for_image.nil?
    puts '3 [DELAYED] if video text available -> generate image '
    # generate_one_genai_image_from_image_description! if genai_input_for_image.to_s.length > 20
    generate_ai_images! if genai_input_for_image.to_s.length > 20 # && translated_story.primogenito?
    puts '4 [NOW] if translation is populated => trigger Text2Speech (NOW)'
    generate_audio_transcript if translated_text.to_s.length >= 5
  end

  def translated_text_for_speech
    # remove asterisks and other ugly stuff which is not nice to HEAR.
    translated_text.gsub(/\*/,'')
  end

  def generate_audio_transcript!()
    generate_audio_transcript( force: true)
  end
  def generate_audio_transcript(opts={})
    opts_force = opts.fetch :force, false

    if self.mp3_audio.attached? and (not opts_force)
      puts "MP3 already attached - skipping"
      return nil
    end
    #str = translated_text
    ret_file = nil
    begin 
      # This can yield problems!
      ret_file = synthesize_speech(translated_text_for_speech, self.language) 
    rescue
      puts("synthesize_speech(): Some exception translating to #{self.language}: #{$!}")
    end
    puts 'To start we use the file (which is non reentrant and not thread safe), then we make it better by passing thje decoded base64 directly for ActiveStorage'
    puts "Habemus: ret_file=#{ret_file}"
    # and some other validation
    is_file_valid = ret_file.is_a? String
    if is_file_valid
      # https://stackoverflow.com/questions/12017694/content-type-for-mp3-download-response
      # To encourage the browser to download the mp3 rather then streaming, do Content-Disposition: filename="music.mp3"'
      self.mp3_audio.attach(io: File.open(ret_file), filename: ret_file) # , content_type: 'audio/mpeg', identify: false)
    end
    return ret_file
  end

  def generate_ai_images!(gcp_opts = {})
    opts_force = gcp_opts.fetch :force, false
    # puts 'TODO if multiple images then write MANY images :)'
    # genai_input_for_image
    if opts_force or translated_story.primogenito? # 
      puts("generate_ai_images(force=#{opts_force}, pg=?): Im primogenito (or you called me with force=true) -> generating images")
      # first born: create them
      multiple_images = genai_compute_multiple_images_by_decription(p_images, genai_input_for_image, gcp_opts)
    else
      # I'm not the first born, I should copy images from it.
      puts("generate_ai_images(): Im NOT primogenito -> copying from PrimoGenito")
      copy_images_from_primogenito_sp
      # return 1040 # TODO: in carlessian numeric
      # copy_images_from(translated_story.primogenito)
    end
    # single_image = genai_compute_single_image_by_decription(p_image1, genai_input_for_image, gcp_opts)
  end

  def copy_images_from_primogenito_sp
    ts1 = translated_story.primogenito
    return :already if p_image1.attached?

    # bigbro has image, lets copy by story_index
    # story_ix1 = sp1.story_index
    # only ONE element. The TAKE transforms the relation in first elemnt:
    # https://stackoverflow.com/questions/12135745/what-is-the-fastest-way-to-find-the-first-record-in-rails-activerecord
    puts("SP(#{id}).copy_images_from_primogenito_sp(story_index=#{story_index})")
    # ATTENTION I'm afraid its copying always the SAME image over and over, as if story_index is not working
    sp1 = StoryParagraph.where(story_index: story_index, story_id: story.id).take

    return :sp_not_found unless sp1.is_a?(StoryParagraph)

    raise "Unmatching story_index before copy!" unless sp1.story_index == self.story_index

    # copy paro paro - https://stackoverflow.com/questions/54203886/how-to-copy-one-object-from-one-model-to-another-model-with-rails-activestorage
    puts("Saving image from primogenito SP.#{sp1.id} --> to this SP.#{id} - both with story_index = #{sp1.story_index}//#{self.story_index}")
    p_image1.attach(sp1.p_image1.blob) # attached_image === p_image1
    save
  end

  # Alias :)
  def fix
    copy_images_from_primogenito_sp unless translated_story.primogenito?
    after_creation_magic
  end

  def fix!
    generate_ai_images!
  end

  def flag
    waving_flag(language)
  end

  # TODO: fix typo
  def self.available_languages
    AVAIL_LANGUAGES
  end

  def self.emoji
    '📜'
  end

  def write_translated_content_for_paragraph(_opts = {})
    if language == 'en'
      # doesnt need translation :)
      puts("Sp.write_translated_content_for_paragraph(): I dont need this as translating to EN so no GTranslate API being called..")
      self.translated_text = original_text
      self.internal_notes = "#{self.internal_notes}\n write_translated_content_for_paragraph(en): skipping translation and just copying paro-paro!"
    else
      self.translated_text = google_translate(original_text, language) # language
    end
    save
  end

  def generate_genai_text_for_paragraph(_opts = {})
    puts 'generate_genai_text_for_paragraph(): START'
    kid = story.kid
    my_style = _opts.fetch :style, 'Pixar'

    self.genai_input_for_image = "Imagine a #{kid.visual_description}. Beside #{kid.akkusativ}, #{original_text}, in the style of #{my_style}"
    puts "Proposed genai_input_for_image for SP.#{id}: #{yellow genai_input_for_image}"
    ret = save
    if ret
      puts 'generate_genai_text_for_paragraph() SAVE OK!'
    else
      puts "generate_genai_text_for_paragraph() SAVE ERROR: #{errors.full_messages}"
    end
  end

  def cleaned_up_translated_text
    translated_text.gsub(/\*\*(A[a-z]+ [12345])\*\*/, '<b class="story_act opacity-75" ><u>\1</b></u>').gsub('**',
                                                                                                             '').html_safe
  end

  def to_s
    "StoryParagraph.#{id} from Story(#{story_id}) and TransStory(#{translated_story_id})"
  end

end

app/controllers/story_paragraphs_controller.rb
class StoryParagraphsController < ApplicationController
  before_action :set_story_paragraph, only: %i[show edit update destroy regenerate_images gen_audio]

  # GET /story_paragraphs or /story_paragraphs.json
  def index
    @story_paragraphs = StoryParagraph.all
    # efficient from https://stackoverflow.com/questions/68646374/how-to-get-the-all-unique-value-using-foreign-key-in-rails
    @stories_with_paragraphs = StoryParagraph.pluck('story_id').uniq
  end

  # GET /story_paragraphs/1 or /story_paragraphs/1.json
  def show; end

  # GET /story_paragraphs/new
  def new
    @story_paragraph = StoryParagraph.new
  end

  # GET /story_paragraphs/1/edit
  def edit; end

  # POST /story_paragraphs or /story_paragraphs.json
  def create
    @story_paragraph = StoryParagraph.new(story_paragraph_params)

    respond_to do |format|
      if @story_paragraph.save
        format.html do
          redirect_to story_paragraph_url(@story_paragraph), notice: 'Story paragraph was successfully created.'
        end
        format.json { render :show, status: :created, location: @story_paragraph }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story_paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /story_paragraphs/1 or /story_paragraphs/1.json
  def update
    respond_to do |format|
      if @story_paragraph.update(story_paragraph_params)
        format.html do
          redirect_to story_paragraph_url(@story_paragraph), notice: 'Story paragraph was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @story_paragraph }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story_paragraph.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /story_paragraphs/1 or /story_paragraphs/1.json
  def destroy
    @story_paragraph.destroy

    respond_to do |format|
      format.html { redirect_to story_paragraphs_url, notice: 'Story paragraph was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def regenerate_images
    # @story_paragraph = StoryParagraph.find(params[:id])
    @story_paragraph.delete_all_images
  end

  def gen_audio
    @story_paragraph.generate_audio_transcript
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_story_paragraph
    @story_paragraph = StoryParagraph.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def story_paragraph_params
    params.require(:story_paragraph).permit(:story_index, :original_text, :genai_input_for_image, :internal_notes,
                                            :translated_text, :language, :story_id, :rating)
  end
end

app/helpers/story_paragraphs_helper.rb
module StoryParagraphsHelper
  def render_excerpt(sp)
    raise 'Wrong object' unless sp.is_a? StoryParagraph

    link_to "#{sp.story_index} #{sp.flag} #{sp.original_text.first(30)}..", sp
  end

  def render_mp3_button(sp, opts={})
    # https://edgeguides.rubyonrails.org/active_storage_overview.html#attaching-files-to-records
    file = sp.mp3_audio
    opts_autoplay = opts.fetch(:autoplay, false)
    opts_muted = opts.fetch( :muted, false)
    autoplay_str = opts_autoplay ? 'autoplay' : ''
    muted_str = opts_muted ? 'muted' : ''
    if sp.mp3_audio.attached?
      #return #content_tag('a',  class: "btn btn-outline-success")
      #'<button type="button" class="btn btn-outline-success">🎶 Play</button>'.html_safe
      #ret = link_to '🎶 Play me', rails_blob_path(file, disposition: "attachment") , class: "btn btn-outline-success"
      #ret += '<audio src="'+rails_blob_path(file, type: "audio")+'" type="audio/mpeg" controls> Your browser does not support the audio element. </audio>'

      # Note: Note: Chromium browsers do not allow autoplay in most cases. However, muted autoplay is always allowed.

      # DEF aps/mu=#{autoplay_str}/#{muted_str}
      # playbackRate DOESNT WORK try: playbackRate='1.5'
      ret = "<audio controls #{autoplay_str} #{muted_str}  src='#{ rails_blob_path(sp.mp3_audio, type: "audio") rescue nil }' type='audio/mpeg' >
          Your browser does not support the audio element.
        </audio>"
      ret.html_safe
    else
      return '🔕'
    end
  end
end

app/views/story_paragraphs/_form.html.erb
<%= form_with(model: story_paragraph, multipart: true) do |form| %>
  <% if story_paragraph.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(story_paragraph.errors.count, "error") %> prohibited this story_paragraph from being saved:</h2>

      <ul>
        <% story_paragraph.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :story_index, style: "display: block" %>
    <%= form.number_field :story_index %>
  </div>

  <div>
    <%= form.label :original_text, style: "display: block" %>
    <%= form.text_area :original_text %>
  </div>

  <div>
    <%= form.label :genai_input_for_image, style: "display: block" %>
    <%= form.text_area :genai_input_for_image %>
  </div>

  <div>
    <%= form.label :internal_notes, style: "display: block" %>
    <%= form.text_area :internal_notes %>
  </div>

  <div>
    <%= form.label :translated_text, style: "display: block" %>
    <%= form.text_area :translated_text %>
  </div>

  <div>
    <%= form.label :language, style: "display: block" %>
    <%= form.text_field :language %>
  </div>

  <div>
    <%= form.label :story_id, style: "display: block" %>
    <%= form.text_field :story_id %>
  </div>
  <div>
    <%= form.label :translated_story_id, style: "display: block" %>
    <%= form.text_field :translated_story_id %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/story_paragraphs/_story_paragraph.html.erb
<div id="<%= dom_id story_paragraph %>">
  <!-- some bootstrap magic .. -->
  <%#= render partial: 'attachments/bootstrap_attachment_view', locals: {attachment: story_paragraph.p_image1 } %>

  <%#= render partial: 'attachments/bootstrap_four_images',
        locals: {four_attachments: [story_paragraph.p_image1, story_paragraph.p_image2, story_paragraph.p_image3, story_paragraph.p_image4] } %>
  <%= render partial: 'attachments/bootstrap_multiple_images', locals: {images: story_paragraph.p_images } %>

  <p>
    <strong>Image1234 (4 single):</strong>
    1<%#= render_image_if_attached(story_paragraph.p_image1) %>
    2<%#= render_image_if_attached(story_paragraph.p_image2) %>
    3<%#= render_image_if_attached(story_paragraph.p_image3) %>
    4<%#= render_image_if_attached(story_paragraph.p_image4) %>
  </p>
  <p>
    <strong>mp3_audio (NEW!) attached?:</strong>
<% if story_paragraph.mp3_audio.attached? %>
    <%#= story_paragraph.mp3_audio %>
    <%= link_to rails_blob_path(story_paragraph.mp3_audio, disposition: "attachment") do %>
          🎶 Download MP3 file
        <% end %>

<% else %>
  <%= link_to("Generate Audio NOW!", "/story_paragraphs/#{story_paragraph.id}/gen_audio", class: "btn btn-outline-dark") %>
  <%= link_to("Generate Audio LATER", "/story_paragraphs/#{story_paragraph.id}/gen_audio?delay=true", class: "btn btn-light") %>
<% end %>
    </p>



  <p>
    <strong>Story index:</strong>
    <%= story_paragraph.story_index %>
  </p>

  <p>
    <strong>Original text:</strong>
    <%= story_paragraph.original_text %>
  </p>

  <p>
    <strong>Genai input for image:</strong>
    <%= story_paragraph.genai_input_for_image %>
  </p>

  <p>
    <strong>Internal notes:</strong>
    <%= story_paragraph.internal_notes %>
  </p>

  <p>
    <strong>Translated text:</strong>
    <%= story_paragraph.translated_text %>
  </p>

  <p>
    <strong>Language:</strong>
    <%= story_paragraph.language %>
  </p>

  <p>
    <strong>Story (OLD):</strong>
    <%= link_to story_paragraph.story,story_paragraph.story %>
  </p>
  <p>
    <strong>Translated Story (new):</strong>
    <%= link_to story_paragraph.translated_story,story_paragraph.translated_story %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= story_paragraph.rating %>
  </p>

</div>

app/views/story_paragraphs/edit.html.erb
<h1>Editing story paragraph</h1>

<%= render "form", story_paragraph: @story_paragraph %>

<br>

<div>
  <%= link_to "Show this story paragraph", @story_paragraph %> |
  <%= link_to "Back to story paragraphs", story_paragraphs_path %>
</div>

app/views/story_paragraphs/gen_audio.html.erb
<h1>🎶 Generating Mp3</h1>

Thanks for your patience.

@story_paragraph: <kbd><%= @story_paragraph %></kbd>

<h2>Audio content </h2>

<i><%= @story_paragraph.translated_text_for_speech %>
</i>
<h2> MP3 attachment </h2>



<% if  @story_paragraph.mp3_audio.attached? %>
    🎶 Habemus audium! representable?
    <%= @story_paragraph.mp3_audio %>
    <div class="player btn btn-outline-secondary">
        <%= audio_tag rails_blob_url(@story_paragraph.mp3_audio) %>
        Play
    </div>

    <% file =  @story_paragraph.mp3_audio
       if file.representable? %>
        <%= image_tag file.representation(resize_to_limit: [100, 100]) %>
      <% else %>
        <%= link_to rails_blob_path(file, disposition: "attachment") do %>
          <%#= image_tag "logo.png", alt: "Download file" %>
          Download file
        <% end %>
      <% end %>

<% else %>
    Nada :(
<% end %>

<h2>Nice links</h2>

<p>
  Back to the Story: <%= link_to @story_paragraph.story  %>
</p>
<p>
  Back to the TranslatedStory <%= link_to @story_paragraph.translated_story %>
</p>

<!-- https://stackoverflow.com/questions/54048280/how-to-play-audio-files-served-from-rails-active-storage -->
<script>
$(document).ready(function() {
    $(".player").click(function() {
        $(this).children('audio')[0].play();
    });
});
</script>

app/views/story_paragraphs/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "New story paragraph", new_story_paragraph_path %>

<table border=1 >
<% @stories_with_paragraphs.each do |story_id|
    # TODO(ricc): make them efficient with a SQL group by.
     inefficient_story = Story.find(story_id)
     inefficient_story_paragraphs = @story_paragraphs.select{|sp| sp.story_id == story_id }.sort

%>
  <tr>
    <td>
      <%= story_id  %>
    <td>
      <%= link_to inefficient_story.title, inefficient_story  %>
    <td>
      <% inefficient_story_paragraphs.each do |p|  %>
        <%= render_excerpt(p) %><br/>
      <% end %>
  <td>
      <%= link_to "#{StoryParagraph.emoji} SP #{story_id}", "/story_rebuilt/#{story_id}"  %>


<% end  %>
</table>
<!--
<h1>Story paragraphs</h1>

<div id="story_paragraphs">
  <% @story_paragraphs.each do |story_paragraph| %>
    <%= render story_paragraph %>
    <p>
      <%= link_to "Show this story paragraph", story_paragraph %>
    </p>
  <% end %>
</div>
 -->

app/views/story_paragraphs/new.html.erb
<h1>New story paragraph</h1>

<%= render "form", story_paragraph: @story_paragraph %>

<br>

<div>
  <%= link_to "Back to story paragraphs", story_paragraphs_path %>
</div>

app/views/story_paragraphs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @story_paragraph %>

<div>
  <%= link_to "Edit this story paragraph", edit_story_paragraph_path(@story_paragraph) %> |
  <%= link_to "Back to story paragraphs", story_paragraphs_path %>

  <%= button_to "Destroy this story paragraph", @story_paragraph, method: :delete %>
</div>