config/routes.rb
Rails.application.routes.draw do
  # get ':fix', to: 'translated_stories#fix', as: :translated_story

  # For attachments: https://stackoverflow.com/questions/49515529/rails-5-2-active-storage-purging-deleting-attachments
  # WIP
  resources :attachments do
    member do
      get :destroy
      delete :destroy
      delete :regenerate
      delete :destroy_all
      delete :regenerate_all
    end
  end

  resources :translated_stories do
    # needs collections or wont have DFLT CRUD
    # collection do
    # #   # get :fix_translated_story
    #   post :fix_translated_story
    # end
    member do
      # from 2.10.1 https://guides.rubyonrails.org/routing.html#creating-paths-and-urls-from-objects
      get 'fix'
    end
  end
  devise_for :users
  resources :story_templates
  resources :story_paragraphs do
    member do
      get 'gen_audio'
    end
  end
  get 'pages/index'
  get 'pages/about'
  get 'pages/help'

  # AI functionality
  get 'pages/slow_function'
  post 'pages/slow_function'
  get 'pages/ai_test'
  post 'pages/ai_test'

  resources :stories
  resources :kids
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  #  match '//' # => StoryRebuiltControler
  get '/story_rebuilt/:id', to: 'stories#show_rebuilt', as: 'story_rebuilt'

  match '/delayed_job' => DelayedJobWeb, :anchor => false, :via => %i[get post]

  # fix_translated_story_path
  # get '/fix_translated_story', 'translated_story#fix_translated_story', as: :fix_translated_story

  # Defines the root path route ("/")
  root 'pages#index'
end

app/models/translated_story.rb
#
#   create_table "translated_stories", force: :cascade do |t|
# t.string "name" #  TODO translated title :)
# t.bigint "user_id", null: false
# t.bigint "story_id", null: false
# t.string "language"
# t.integer "kid_id"
# t.string "paragraph_strategy"
# t.text "internal_notes"
# t.string "genai_model"
# #
# # ADDED 'translated_title' recently
# ADDED 'cached_completion:float' recently (0..100) but float. nil = -1
##
# t.index ["kid_id"], name: "index_translated_stories_on_kid_id"
# t.index ["story_id"], name: "index_translated_stories_on_story_id"
# t.index ["user_id"], name: "index_translated_stories_on_user_id"
# end

# This is something I should have created A LONG TIME AGO :)
class TranslatedStory < ApplicationRecord
  belongs_to :user # Oops its done in the DB, optional: true
  belongs_to :story
  belongs_to :kid, optional: true
  has_many :story_paragraphs, dependent: :destroy

  # validates :language, presence: true # A TS needs a Story and a Language, STRONGLY.
  validates :score, numericality: { in:  -100..100 }
  validates :language, presence: true,
                       format: { with: AVAIL_LANGUAGE_REGEX,
                                 message: AVAIL_LANGUAGE_MESSAGE }

  validates :story_id, uniqueness: { scope: %i[language paragraph_strategy] }
  validates :paragraph_strategy, presence: true,
                                 format: { with: /\w+-v([\d.]+)/,
                                           message: 'We only support simple-v0.1 and smart-v0.1 at the moment' }
  # , message: 'No spaces, just dash underscores and lower cases'

  # https://api.rubyonrails.org/classes/ActiveRecord/Store.html
  # On 14sep23, I renamed completion_rate to completion_sum so now completion_rate exists in very few dev and prod TS :)
  # But hey, its a hash :)
  store :settings, accessors: [ :cache_images, :cache_audios, :completion_sum, :completion_pct, :n_paragraphs ]

  after_create :fix_missing_attributes
  #  after_save :after_each_save_fix_cheap_missing_attributes
  #

  def self.default_genai_model
    #'text-bison@001'
    'text-bison'
  end

  # after save, many times
  def after_each_save_fix_cheap_missing_attributes
    puts 'after_each_save_fix_cheap_missing_attributes'
    if story.kid_id.nil?
      self.kid_id = story.kid.id
      save
    end
    # same as above but done with robocop
    return unless language.nil? or language == ''

    self.language = story.kid.favorite_language
    save

    true
    # self.language ||= story.kid.favorite_language
  end

  def set_translated_title
    # sleep(10)
    self.translated_title = google_translate(story.title, language)
    save
    # translated_title = "TODO (simulate a google translate from story title =#{story.title})"
  end

  # after create, only once
  def fix_missing_attributes
    puts 'fix_missing_attributes'
    self.kid_id ||= story.kid.id
    self.language ||= story.kid.favorite_language || DEFAULT_LANGUAGE # Italian :)
    self.paragraph_strategy ||= DEFAULT_PARAGRAPH_STRATEGY # 'smart-v0.1' # TODO export as
    append_notes('TranslatedStory.fix_missing_attributes called')
    # delay(queue: 'translated_story::set_translated_title').set_translated_title if translated_title.to_s == ''
    set_translated_title if translated_title.to_s == ''
    self.update_cache(save: true) # unless settings.keys.include?('cache_audios') and settings.keys.include?('cache_images')  # either that or cache_images
    save
  end

  # disabled rubocop as per https://stackoverflow.com/questions/62562455/visual-studio-code-disabling-error-warning-checks-in-for-specific-file-type
  def to_s
    # Damn rubocop! "#{self.emoji} #{name}"
    if translated_title.to_s.size > 1
      "#{flag} #{translated_title}"
    else
      "#{flag} #{TranslatedStory.emoji} #{name}"
    end
  end

  def flag
    waving_flag(self.language)
  end

  def self.emoji
    # 🈳👅 # cant choose between the 2..'
    '🈳' # cant choose between the 2..'
  end

  def paragraphs_with_no_images
    story_paragraphs.map { |x| [x.id, x.image_attached?] }.select { |a| a[1] == false }.map { |a| a[0] }
  end

  def copy_images_from_primogenito!
    return nil if primogenito?
    puts 'TODO(): Ricc I have a feeling theres a bug here as I keep see same images being copied to different paragraphs like the index wouldnt update'
    # BUG Example: https://genai-kids-stories-gcloud-poor-cdlu26pd4q-ew.a.run.app/translated_stories/54
    rets = []
    ts1  = primogenito # different from me
    ts1.story_paragraphs.each do |sp1_i|
      ret = sp1_i.copy_images_from_primogenito_sp
      rets << ret
    end
    rets
  end

  def excerpt(max_size = 35)
    flag + ' ' + translated_title.to_s.gsub('Translation of:', '').first(max_size) + '..'
  end

  # if you call with force: true it forces generation of images..
  def fix!(opts={})
    puts 'Fixing the children paragraphs even if not needed...'
    story_paragraphs.each do |story_paragraph|
      id = story_paragraph.id
      puts "Forcing redo image for #{id}"
      story_paragraph.generate_ai_images!(opts)
    end
  end

  def fix(opts={})
    fix_missing_attributes
    # Check children translated_stories for missing images
    fix_missing_audios
    # =>  [[204, false]]
    if primogenito?
      puts "TS(#{self.id}).fix(): PRIMOGENITO: I'm generating missing images"
      paragraphs_with_no_images.each do |id|
        puts "Missing image for #{id}"
        StoryParagraph.find(id).generate_ai_images!(opts)
      end
    else
      puts "TS(#{self.id}).fix(): SECONDOGENITO: I'm copying existing images from priomogenito.. and maybe fix him later"
      # TODO: fix primogenito first..

      copy_images_from_primogenito!
    end
  end

  def simple_paragraphs(_algorithm_version)
    story.simple_paragraphs
  end

  def smart_paragraphs(_algorithm_version)
    story.smart_paragraphs
  end

  def polymorphic_paragraphs
    paragraph_strategy_base, paragraph_strategy_version = paragraph_strategy.split('-v') rescue [nil, nil]

    case paragraph_strategy_base # paragraph_strategy: simple-v0.1
      when 'simple'
        simple_paragraphs(paragraph_strategy_version)
      when 'smart'
        smart_paragraphs(paragraph_strategy_version)
      else
        puts "Unknown typology '#{paragraph_strategy_base}'.."
        []
    end
  end

  def generate_polymorphic_paragraphs(_opts = {})
    # lang = _opts.fetch(:lang, DEFAULT_LANGUAGE)
    # lang = self.language
    key = _opts.fetch(:key, GOOGLE_TRANSLATE_KEY2)

    cached_pars = polymorphic_paragraphs

    # find or create by story and lang :)

    puts "Story.generate_paragraphs(). Size: #{cached_pars.size}"
    # return if StoryParagraph.find(story_id: id).count > 0
    cached_pars.each_with_index do |p, _ix|
      story_ix = _ix + 1 # start from 1.. Im pretty sure Im gonna regret this :)
      puts "⅞T0d0 #{StoryParagraph.emoji} [#{story_ix}] #{p}"
      # StoryParagraph(story_index: integer, original_text: text, genai_input_for_image: text,
      sp = StoryParagraph.create(
        language: self.language,
        story_index: story_ix,
        story_id: story.id,
        internal_notes: "Created via TranslatedStory.generate_polymorphic_paragraphs on #{Time.now}\n",
        original_text: p,
        translated_story_id: id
      )
      puts(sp)
      puts "SP ERROR: #{sp.errors.full_messages}" unless sp.save
    end
  end

  # calculate if its first born
  def first_born
    story.first_translated_story
  end

  def first_born?
    story.first_translated_story.id == id
  end

  # TODO: make them aliases :)
  def primogenito?
    first_born?
  end

  def primogenito
    first_born
  end

  def big_brother
    first_born
  end

  # TODO move to helper like I did for the cache audio video :)
  def story_paragraphs_images_succint
    ret = 'images['
    story_paragraphs.each do |sp|
      ret += sp.attached? ? '✅' : '❌' # 🔷👍😥
    end
    ret + ']'
  end

  def self.fix_all
    puts 'This is HUGE! Fixing ALL Translated Stories! This should be a bkgd job, btw!'
    autofix
  end

  # The good question is - when should I invoke this? After creation of object? After creation of paragraphs? We'll find the right oplace Im sure.
  def update_cache(opts={})
    opts_save = opts.fetch :save, true
    puts "DEBUG: Updating the cache of images and videos of this TS. Note that audio belongs to translated story, while the images should be equal for all translations hence be attached to story itself."
    self.cache_images = self.story_paragraphs.map{|sp| [sp.story_index, sp.id, sp.image_attached?] }
    self.cache_audios = self.story_paragraphs.map{|sp| [sp.story_index, sp.id, sp.audio_attached?] }
    # 42 # TODO count od the above
    self.n_paragraphs = self.story_paragraphs.count
    self.completion_sum =  self.cache_images.count{|x| x[2] == true } +  self.cache_audios.count{|x| x[2] == true }
    self.completion_pct =  100 * self.completion_sum / (self.cache_images.count + self.cache_audios.count ) rescue -1 # should be 0..1
    self.cached_completion = self.completion_pct
    self.save if opts_save
  end

  def fix_missing_audios
    puts "DEB Lets see if this works.."
    puts "TODO use cache if needed"
    self.story_paragraphs.each { |sp|
      if sp.audio_attached?
        puts "ts(#{id}).fix_missing_audios(): Skipping as already audio attached: #{sp} sp.audio_attached? = #{sp.audio_attached?}"
      else
        sp.generate_audio_transcript()
      end
    }
    update_cache
    true
  end

  def self.update_cache_for_all!()
    puts('This should be a pretty SAFE yet compute intensive job.')
    TranslatedStory.all.each do |ts|
      ts.update_cache(save: true)
    end
  end

end

app/controllers/translated_stories_controller.rb
class TranslatedStoriesController < ApplicationController
  before_action :set_translated_story, only: %i[show edit update destroy]

  # GET /translated_stories or /translated_stories.json
  #     limit_per_page = 6
  # @stories = Story.all.active.order('score DESC, created_at DESC').paginate(page: params[:page], per_page: limit_per_page)
  # @total_pages = @stories.count / limit_per_page

  def index
    limit_per_page = 10
    @pluralized_entity = 'translated_stories'
    #@translated_stories = TranslatedStory.all
    ## cached_completion
    @translated_stories = TranslatedStory.all.order('cached_completion DESC, score DESC, created_at DESC').paginate(page: params[:page], per_page: limit_per_page)
    @total_pages = @translated_stories.count / limit_per_page
  end

  # GET /translated_stories/1 or /translated_stories/1.json
  def show
    #  hidden @translated_story
    @story_paragraphs = StoryParagraph.where(translated_story_id: @translated_story.id).order('story_index ASC')
    # TODO: .sort by
    @execute_now = params[:execute_now] == 'true'
  end

  # GET /translated_stories/new
  def new
    @translated_story = TranslatedStory.new(
      language: params['language'],
      story_id: params['story_id'],
      name: params['name'],
      internal_notes: params['internal_notes']
    )
  end

  # GET /translated_stories/1/fix
  def fix # _translated_story
    @translated_story = begin
      TranslatedStory.find(params[:id])
    rescue StandardError
      nil
    end
    @ret = begin
      if params.fetch(:delay, '') == 'true'
        @translated_story.delay(queue: 'translated_stories_controller::fix').fix
      else
        @translated_story.fix
      end
    rescue StandardError
      nil
    end
  end

  # GET /translated_stories/1/edit
  def edit; end

  # POST /translated_stories or /translated_stories.json
  def create
    @translated_story = TranslatedStory.new(translated_story_params)

    respond_to do |format|
      if @translated_story.save
        format.html do
          redirect_to translated_story_url(@translated_story), notice: 'Translated story was successfully created.'
        end
        format.json { render :show, status: :created, location: @translated_story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @translated_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translated_stories/1 or /translated_stories/1.json
  def update
    respond_to do |format|
      if @translated_story.update(translated_story_params)
        format.html do
          redirect_to translated_story_url(@translated_story), notice: 'Translated story was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @translated_story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @translated_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translated_stories/1 or /translated_stories/1.json
  def destroy
    @translated_story.destroy

    respond_to do |format|
      format.html { redirect_to translated_stories_url, notice: 'Translated story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_translated_story
    @translated_story = TranslatedStory.find(params[:id])  rescue redirect_to( translated_stories_url, notice: "Translated Story #{params[:id]} error: #{ $! }")
  end

  # Only allow a list of trusted parameters through.
  def translated_story_params
    params.require(:translated_story).permit(:name, :user_id, :story_id, :language, :kid_id, :paragraph_strategy, :translated_title,
                                             :translated_story, :internal_notes, :genai_model, :score)
  end
end

app/helpers/translated_stories_helper.rb
module TranslatedStoriesHelper
  # <table border="0" >

  # #{ @story_paragraphs.each do |p| }

  # #{ end }
  # </table>
  #
  #
  # INPUT: [[1, 348, true], [2, 349, false], [3, 350, true], [4, 351, false], [5, 352, false], [6, 353, false], [7, 354, true]]
  # OUTPUT:
  def render_cached_info(ts, symbolic_method, opts={})
    opts_verbose = opts.fetch :verbose, false
    return :TODO if opts_verbose

    ts_generic_array = ts.send(symbolic_method) # Gets array like
    emoji_nope = '❌'
    emoji_yup = case symbolic_method
      when :cache_audios
        '🎶' # missing audio could be: 🔕 (awesome)
      when :cache_images
        '🏞️' # missing image could be: 🌌 (meh)
      else
        'unrecognize'
      end
      content_tag 'tt', (ts_generic_array.map{|x| x[2] ? emoji_yup : emoji_nope}.join '') rescue '🤷🏼‍♀️'
  end

  def render_working_story_paragraph(p)
    if p.nil?
      return '<tr>
        <th>IX
        <th>Original 🇬🇧
        <th>Lang / Pic
        <th>Translated
        <th>Opts
      </tr>'.html_safe
    end
    "<tr>
      <td>#{link_to p.story_index, p}🔷
      <td width='45%' class='story' >#{p.original_text}
      <td>
        #{p.flag}
        #{render_image_if_attached(p.p_image1, verbose: false)}

      <td width='45%' class='story' >#{p.translated_text or "<pre>StoryParagraph.find(#{p.id}).after_creation_magic</pre>".html_safe}
      <td>
          #{link_to p.id, p}
          #{link_to '✍🏿', edit_story_paragraph_path(p)}
         ".html_safe
  end

  def render_completion_pct(translated_story)
    pct = translated_story.completion_pct
    style = (pct == 0) ? 'bg-secondary' : 'bg-success'
    pct ?
      "<kbd class='#{style}' >#{pct.to_s.rjust(2,'0')}</kbd>".html_safe :
      '-'
  end

end

app/views/translated_stories/_form.html.erb
<%= form_with(model: translated_story, multipart: true) do |form| %>
  <div class='form-group' >
    <% if translated_story.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(translated_story.errors.count, "error") %> prohibited this translated_story from being saved:</h2>

        <ul>
          <% translated_story.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block", class: 'form-control-sm' %>
      <%= form.text_area :name, class: 'form-control form-control-sm' %>
    </div>

    <div>
      <%= form.label :translated_title, style: "display: block", class: 'form-control-sm' %>
      <%= form.text_field :translated_title, class: 'form-control form-control-sm' %>
    </div>



    <div>
      <%= form.label :user_id, style: "display: block", class: 'form-control' %>
      <%#= form.text_field :user_id %>
      <%= form.select :user_id, options_for_select(User.all.collect{ |user| [user.name, user.id] }), {class: 'form-control'}, {} %>

    </div>

    <div>
      <%= form.label :story_id, style: "display: block" %>
      <%#= form.select :story_id, options_for_select(Story.all.collect{ |story| [story.title, story.id] }), selected: params['story_id'], {} %>
      <%= form.select :story_id, options_for_select(
                                                    Story.all.collect{ |story| [story.title, story.id] },
                                                     @translated_story.story_id),
                                                     {} , {}
      %>
    </div>
    <div>
      <%= form.label :language, style: "display: block" %>
      <%= form.text_field :language %>
    </div>

  <!-- this is a hidden dependency, should be set after story :) or nothing at all :)
    <div>
      <%= form.label :kid_id, style: "display: block" %>
      <%= form.number_field :kid_id %>
    </div>
  -->
    <div>
      <%= form.label :paragraph_strategy, style: "display: block" %>
      <%= form.text_field :paragraph_strategy, required: true, class: 'form-control', value:Story.default_paragraph_strategy %>

    </div>

   <div>
    <%= form.label :score, style: "display: block", class: "form-label" %>
    <%= form.number_field :score %>
  </div>

    <div>
      <%= form.label :internal_notes, style: "display: block" %>
      <%= form.text_area :internal_notes %>
    </div>

    <div>
      <%= form.label :genai_model, style: "display: block" %>
      <%#= form.text_field :genai_model %>
      <%= form.text_field :genai_model, required: true, class: 'form-control', value:TranslatedStory.default_genai_model  %>

    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/translated_stories/_translated_story-carousel.html.erb
<%
  kid = translated_story.story.kid

%>
<div id="<%= dom_id translated_story %>">
  <h1>🎠 <%= waving_flag translated_story.language %>
    <%= translated_story.translated_title %>
  </h1>

  <div class='200-px-wide' >
    <div id="carouselExampleCaptions" class="carousel slide carousel-dark" data-bs-ride="carousel" data-bs-interval="10000" data-bs-wrap="false" >
      <div class="carousel-indicators">
          <% @story_paragraphs.each_with_index do |sp, ix| %>
            <% if ix == 0 %>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <% else  %>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="<%= ix %>" aria-label="Slide <%= ix+1 %>"></button>
            <% end %>
          <% end %>

        </div>
        <div class="carousel-inner">
          <!-- start of carousel https://getbootstrap.com/docs/5.0/components/carousel/ -->
          <% @story_paragraphs.each_with_index do |sp, ix|
              addon_if_first = (ix==0) ? ' active ' : ''
          %>
            <% if ix == 0 %>
              <div class="carousel-item active">
            <% else %>
              <div class="carousel-item">
            <% end %>
              <div class="image-container" >
              <!-- from Bard -->
                <%= image_tag(sp.p_image1,
                      class: "d-block w-100 ricc-transparent",
                      alt: 'Image Descr',
                      style: 'opacity: 0.5;' ) if  sp.p_image1.attached?  %>
              </div>
              <div class="carousel-caption d-md-block small">
                <h5>🌁 Slide <%= ix + 1%> 🌁</h5>
                <!-- if you put autoplay true, ALL audios play at same time and its HORRIBLE :) -->
                <%= render_mp3_button sp, autoplay: false %>
                <p class='text-dark h5' ><%= sp.cleaned_up_translated_text %></p>

              </div>

          </div>
          <% end %>
          <!-- Note:
          the 'd-none' makes ot disappear if too small, see https://stackoverflow.com/questions/70484901/bootstrap-5-carousel-caption-text-disappears-when-the-website-is-seen-on-a-small
          -->
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div>
      <p class="lead"><em>
        Dear parent, if you cant read them on the carousel (requires a big screen for now) see translated story here too..
      </em></p>
      <ul class="list-group small">
        <% @story_paragraphs.each_with_index do |sp, ix| %>
          <li class="list-group-item "><%= sp.cleaned_up_translated_text %> <%= render_mp3_button sp %>
      </li>
        <% end %>
      </ul>
    </div>
</div>

app/views/translated_stories/_translated_story.html.erb
<% if params[:style] == 'old' %>
  <!-- OLD -->
  <%= link_to 'For classic 🅱️ style, click here', "/translated_stories/#{translated_story.id}" %>
  <%= link_to 'For new 🎠 Carousel style, click here', "/translated_stories/#{translated_story.id}?style=carousel" %>

  <%#= render partial: 'translated_stories/translated_story-old', locals: {translated_story: translated_story }  %>
<% elsif params[:style] == 'carousel' %>
  <!-- carousel (new!) -->
  <%= render partial: 'translated_stories/translated_story-carousel', locals: {translated_story: translated_story }  %>

  <%#= link_to 'For old 👴🏾 style, click here', "/translated_stories/#{translated_story.id}?style=old" %>
  <%= link_to 'For classic 🅱️ style, click here', "/translated_stories/#{translated_story.id}" %>


<% else  %>
  <!-- normal, good, bootstrap list -->
  <%#= link_to 'For old 👴🏾 style, click here', "/translated_stories/#{translated_story.id}?style=old" %>
  <%= link_to 'For new 🎠 Carousel style, click here', "/translated_stories/#{translated_story.id}?style=carousel" %>

  <%= render partial: 'translated_stories/translated_story-bootstrap', locals: {translated_story: translated_story }  %>
<% end %>

app/views/translated_stories/edit.html.erb
<h1>Editing translated story</h1>

<%= render "form", translated_story: @translated_story %>

<br>

<div>
  <%= link_to "Show this translated story", @translated_story %> |
  <%= link_to "Back to translated stories", translated_stories_path %>
</div>

app/views/translated_stories/fix.html.erb
<%# @notice = 'ds fd ' %>
<h2>Fixed TS # ... </h2>
Fixing stuff...

<%= link_to @translated_story %>

Fix: <br/>
<%= @translated_story.fix() %>

app/views/translated_stories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Well-done Translated stories</h1>

Showing only FULLY complete stories :)
But since I cant do the check in the DB (as WHERE) since its JSON this won't work great with pagination :)

<%= render partial: 'layouts/pagination_tab', locals: {entity: 'translated_stories' } %>

<div id="translated_stories">
    <table>
      <th>Links
      <th>Kiddo
      <th>Compl
      <th>etion
      <th>Score
      <th>Translated Story
      <th>Original Story
  <% @translated_stories.each do |translated_story|
        #next unless (translated_story.completion_pct >= 99 rescue false)

  %>

    <tr>
      <td>
        <%= link_to "👁️", translated_story %>
        <%= link_to "🔏", edit_translated_story_path(translated_story) %>
        <%= button_to "💣", translated_story, method: :delete %>
      <td>
        <%= link_to translated_story.kid,translated_story.kid %>
      <td>
      <% if translated_story.completion_pct %>
        <kbd class='bg-success' ><%= translated_story.completion_pct %></kbd>
        <% end %>
        <!-- for debug to compare..-->
      </td>
      <td>
        <small ><%= translated_story.cached_completion or 'nil' %></small>
      <td>
        <kbd class='bg-primary' ><%= translated_story.score %></kbd>
      <td>
        <%= link_to translated_story,translated_story %>
      <td>
        <kbd class='bg-primary' ><%= translated_story.story.score %></kbd>
        <%= link_to translated_story.story,translated_story.story %>
    </tr>
  <% end %>
  </table>
</div>

<%= link_to "New translated story", new_translated_story_path %>

app/views/translated_stories/new.html.erb
<h1>New translated story</h1>

<%= render "form", translated_story: @translated_story %>

<br>

<div>
  <%= link_to "Back to translated stories", translated_stories_path %>
</div>

app/views/translated_stories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @translated_story %>

<div class="btn-group" role="group" aria-label="Basic mixed styles example">
  <%= link_to "Back", translated_stories_path, class: 'btn btn-success' %>
  <%= link_to "🔏 Edit", edit_translated_story_path(@translated_story), class: 'btn btn-warning' %> |
  <%= button_to "Destroy", @translated_story, method: :delete, class: "btn btn-danger" %>
</div>