config/routes.rb
Rails.application.routes.draw do
  # get ':fix', to: 'translated_stories#fix', as: :translated_story

  # For attachments: https://stackoverflow.com/questions/49515529/rails-5-2-active-storage-purging-deleting-attachments
  # WIP
  resources :attachments do
    member do
      get :destroy
      delete :destroy
      delete :regenerate
      delete :destroy_all
      delete :regenerate_all
    end
  end

  resources :translated_stories do
    # needs collections or wont have DFLT CRUD
    # collection do
    # #   # get :fix_translated_story
    #   post :fix_translated_story
    # end
    member do
      # from 2.10.1 https://guides.rubyonrails.org/routing.html#creating-paths-and-urls-from-objects
      get 'fix'
    end
  end
  devise_for :users
  resources :story_templates
  resources :story_paragraphs do
    member do
      get 'gen_audio'
    end
  end
  get 'pages/index'
  get 'pages/about'
  get 'pages/help'

  # AI functionality
  get 'pages/slow_function'
  post 'pages/slow_function'
  get 'pages/ai_test'
  post 'pages/ai_test'

  resources :stories
  resources :kids
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  #  match '//' # => StoryRebuiltControler
  get '/story_rebuilt/:id', to: 'stories#show_rebuilt', as: 'story_rebuilt'

  match '/delayed_job' => DelayedJobWeb, :anchor => false, :via => %i[get post]

  # fix_translated_story_path
  # get '/fix_translated_story', 'translated_story#fix_translated_story', as: :fix_translated_story

  # Defines the root path route ("/")
  root 'pages#index'
end

app/models/story.rb
# frozen_string_literal: true

#   create_table "stories", force: :cascade do |t|
# t.string "title"
# t.text "genai_input"
# t.text "genai_output"
# t.text "genai_summary"
# t.text "internal_notes"
# t.integer "user_id"
# t.bigint "kid_id", null: false
# t.index ["kid_id"], name: "index_stories_on_kid_id"
#       , :active
# end

# ATTACCHMENTS:
# * `cover_image`

class Story < ApplicationRecord
  include AiImageable

  # For Story and Kid, maybe I should raise a Concern?? :)
  scope :active, -> { where('active = TRUE') }
  scope :inactive, -> { where('active = FALSE') }

  belongs_to :kid
  #  has_one_attached :cover_image
  has_many :story_paragraphs
  has_many :translated_stories

  has_one_attached :cover_image, service: :google do |attachable|
    attachable.variant :thumb, resize_to_limit: [200, 200]
  end
  # GCS test :)
  has_many_attached :additional_images, service: :google
  has_many_attached :paragraphs_images

  # validates :title, uniqueness: { scope: :user_id }
  validates :score, numericality: { in: -100..100 }

  # https://stackoverflow.com/questions/33890458/difference-between-after-create-after-save-and-after-commit-in-rails-callbacks
  # after_create :delayed_job_genai_mag
  # doesnt work since its unauthorized maybe different process  -> different ENVs?
  # #<Net::HTTPUnauthorized 401 Unauthorized readbody=true>

  # after_save  OK with delayed, but not with
  # after_save :delayed_job_genai_magic # The right way

  # This works
  # # Note: after_save creates a loop!!!
  after_create :genai_magic # DEBUG
  before_destroy :cleanup_story_dependencies

  def self.emoji
    '📚'
  end

  def cleaned_up_title
    title.gsub('**', '')
  end

  # Implemented on father
  # def delete_all_images
  #   # Story version :)
  #   self.cover_image.purge
  # end

  # seby_story1.attach_cover('seby-firefighter.png')
  def attach_cover(filename, _opts = {})
    # self.cover_image =   cover_image: attachment # File.open("#{STORIES_FIXTURE_IMAGES_DIR}/seby-firefighter.png"), #, filename: 'seby-firefighter.png' )
    cover_image.attach(
      io: File.open("#{STORIES_FIXTURE_IMAGES_DIR}/#{filename}"),
      metadata: { function: 'attach_cover' },
      filename:
    )
  end

  def attached_stuff_info
    {
      cover_image: super_attached_stuff_info(:cover_image),
      additional_images: super_attached_stuff_info(:additional_images),
    }
  end

  def self.test_image_attachment(_path = nil)
    # path ||= Rails.root.join('app/assets/images/kids/doll.jpg')
    # filename = 'test_image_attachment_doll.png'
    {
      io: File.open(Rails.root.join('app/assets/images/kids/doll.jpg')),
      filename: 'doll.jpg',
      # content_type: 'image/jpeg',
      identify: true,
    }
  end

  # Translation to a language (which autotriggers after )
  def translate_to(language_in_symbol_or_string_format = :en)
    lang = language_in_symbol_or_string_format.to_s
    puts 'translate_to(): TODO(Ricc): when this works, refactor the creation button to just leverage this with all meaningful defaults - should just be a language choice and a click :)'
    if TranslatedStory.where(story_id: self.id, language: lang).size > 0
      puts "Story##{id} already has a translation in #{lang} -> skipping"
      return true
    end
    puts '🙄 You wish - 👅WIP👅!'
    ts = TranslatedStory.create(
      story_id: self.id,
      paragraph_strategy: Story.default_paragraph_strategy,
      internal_notes: "Created via Story.translate_to appver=#{APP_VERSION}, possibly wrapped in a delayed job..",
      language: lang,
      kid_id: kid.id,
      user_id: self.user_id,
      name: self.title,
      genai_model: TranslatedStory.default_genai_model,
    )
    puts("Created ts: #{ts}")
    n_errors = ts.errors.count
    if n_errors > 0
      puts 'There were some errors:'
      puts("Story(#{id}).translate_to(#{lang}) Errors creating ts: '#{ts.errors.full_messages}'")
    else
      # All good
      puts('All good -> generating now also the poly paragraphs :)')
      ts.delay(queue: 'story::translate_to::after').generate_polymorphic_paragraphs()
    end
    return ts
  end

  def cleanup_story_dependencies
    story_paragraphs.each do |p|
      p.delete
    end
  end

  # Just a test!
  def attach_test_image(opts = {})
    opts_save_afterwards = opts.fetch :save_afterwards, true
    opts_purge_before = opts.fetch :purge_before, true

    # https://stackoverflow.com/questions/45870021/how-to-update-attachment-in-activestorage-rails-5-2
    begin
      cover_image.purge
    rescue StandardError
      :maybe_nothing_topurge
    end # if opts_purge_before
    # cover_image.attach(io: File.open(Rails.root.join('app/assets/images/kids/doll.jpg')),
    #                    filename: 'doll.jpg')
    cover_image.attach(Story.test_image_attachment)
    return unless opts_save_afterwards

    save_ok = save!
    puts("save_ok=#{save_ok} - ERRORS: #{errors.full_messages}")
    puts save_ok
  end

  def simple_paragraphs
    # needs to remove '**Act 1**'
    genai_output.split("\n").reject { |c| c.length < 12 }.map { |x| x.chomp }
  rescue StandardError
    []
    # empty?
  end

  def paragraphs
    # puts "TODO consider also using https://apidock.com/rails/v5.2.3/ActionView/Helpers/TextHelper/split_paragraphs"
    #smart_paragraphs(min_chunk_size = 150) or []
    smart_paragraphs() or []
  end

  def smart_paragraphs(min_chunk_size = 200)
    # TODO(ricc): split intelligently and a bit bigger chuinks
    split_paragraphs_brd(genai_output, min_chunk_size)
    # split_into_chunks_cg(genai_output, min_chunk_size)
  end

  # wrong
  def split_paragraphs_brd(str, min_chunk_size)
    paragraphs = []
    current_paragraph = ''
    str.to_s.each_line do |line|
      if current_paragraph.length >= min_chunk_size
        paragraphs << current_paragraph
        current_paragraph = ''
      end
      current_paragraph += line
    end
    paragraphs << current_paragraph
    # paragraphs
    paragraphs.reject { |c| c.length < 5 }.map { |x| x.chomp }
  end

  def split_into_chunks_cg(str, min_chunk_size)
    paragraphs = str.split("\n")
    chunks = []

    current_chunk = ''
    paragraphs.each do |paragraph|
      if current_chunk.length + paragraph.length <= min_chunk_size
        current_chunk += paragraph + "\n"
      else
        chunks << current_chunk.rstrip unless current_chunk.empty?
        current_chunk = paragraph + "\n"
      end
    end
    # ???
    chunks << current_chunk.rstrip unless current_chunk.empty?
    # chunks
    chunks.reject { |c| c.length < 5 }.map { |x| x.chomp }
  end

  # # Example usage:
  # big_string = "Paragraph 1\nParagraph 2\nParagraph 3\nParagraph 4\nParagraph 5\nParagraph 6"
  # chunks = split_into_chunks(big_string)
  # puts chunks.inspect
  # In this example, the split_into_chunks method takes a string as input and returns an array of chunks. It splits the string into paragraphs using the "\n" delimiter and then loops through the paragraphs. It keeps adding paragraphs to the current_chunk variable as long as the length of the chunk (including the current paragraph) does not exceed 200 characters. Once the length limit is reached, the current chunk is added to the chunks array, and a new chunk is started with the current paragraph.

  # The resulting chunks are stored in the chunks array, and in this example, we print the array using inspect. You can modify the code to suit your specific needs, such as storing the chunks in a variable or performing further processing on them.

  def to_s
    "#{Story.emoji}.#{id} '#{title}'"
  end

  #### MAGIC AI
  #
  def genai_input_size
    genai_input.size
  rescue StandardError
    0
  end

  def genai_output_size
    genai_output.size
  rescue StandardError
    0
  end

  def genai_summary_size
    genai_summary.size
  rescue StandardError
    0
  end

  def title_size
    title.size
  rescue StandardError
    0
  end

  def delayed_job_genai_magic
    Rails.logger.info("delayed_job_genai_magic(): 1. Enqueuing GenAI Magic for Story.#{id}")
    delay(queue: 'story::genai_magic').genai_magic(delay: true)
  end

  def should_compute_genai_output?
    genai_input_size > 10 and genai_output_size < 10
  end

  def should_compute_genai_summary?
    genai_output_size > 10 and genai_summary_size < 10
  end

  def should_autogenerate_genai_input?
    genai_input_size < 11
  end

  def should_compute_genai_images?
    title_size > 10 and !cover_image.attached?
  end

  # to be DELAYed
  # https://github.com/collectiveidea/delayed_job/tree/v4.1.11
  # @story.delay.genai_compute!(@device)
  def genai_magic(opts = {})
    delay = opts.fetch :delay, false
    force = opts.fetch :force, false
    # This function has the arrogance of doing EVERYTHING which needs to be done. It will defer to sub-parts and
    # might take time, hence done with 'delayed_job'
    Rails.logger.info("genai_magic(delay=#{delay}): 2. actually executing GenAI Magic for Story.#{id}")

    gcp_opts = {
      project_id: AI_PROJECT_ID,
      gcloud_access_token: GCauth.instance.token # GCLOUD_ACCESS_TOKEN
    }

    if force or should_autogenerate_genai_input? # total autopilot :)
      puts '🤖10🤖 I have no input -> computing the Guillaume story template (implemented)'
      ret10 = genai_autogenerate_input! # doesnt require GCP :)
    end
    if force or should_compute_genai_output?
      puts '🤖20🤖 I have input but no output -> computing it with Generate API (implemented)'
      ret20 = genai_compute_output!(gcp_opts)
    end
    if force or should_compute_genai_summary?
      puts '🤖30🤖 I have output but no summary -> computing it with Summary API (implemented)'
      ret30 = genai_compute_summary!(gcp_opts)
    end
    if force or should_compute_genai_images?
      puts "🤖40🤖 Exciting! [#{Story.emoji}.#{id}] Trying to compute images with Palm API (implemented)"
      ret40 = genai_compute_images!(gcp_opts)
    end

    # After local Story creation has terminated I trigger a TranslatedStory in English in queue mode

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[show edit update destroy genai_magic]

  # Google proxy gives me an error =>
  # https://stackoverflow.com/questions/65688157/why-is-my-http-origin-header-not-matching-request-base-url-and-how-to-fix
  skip_before_action :verify_authenticity_token

  # GET /stories or /stories.json
  def index
    limit_per_page = 9
    @stories_per_row = 3
    @pluralized_entity = 'stories'
    @stories = Story.all.active.order('score DESC, created_at DESC').paginate(page: params[:page], per_page: limit_per_page)
    @total_pages = @stories.count / limit_per_page
  end

  # GET /stories/1 or /stories/1.json
  def show; end

  def show_rebuilt
    @story = Story.find(params[:id])
    @story_paragraphs = @story.story_paragraphs.sort
    @translate_to = params[:translate_to] # or , nil)
    # if @translate_to do magic in controller?
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  def genai_magic
    # set_story :)
    puts 'Doing some magic here :)'
  end

  # GET /stories/1/edit
  def edit; end

  # POST /stories or /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to story_url(@story), notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1 or /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to story_url(@story), notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1 or /stories/1.json
  def destroy
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_story
    @story = Story.find(params[:id]) rescue redirect_to( stories_url, notice: "Story #{params[:id]} error: #{ $! }")

    # https://stackoverflow.com/questions/2139996/how-to-redirect-to-previous-page-in-ruby-on-rails
    session[:return_to] ||= request.referer

    @already_translated = []
    TranslatedStory.where(story_id: @story.id).each do |ts|
      @already_translated << ts.language
    end
  end

  # Only allow a list of trusted parameters through.
  def story_params
    params.require(:story).permit(:title, :genai_input, :genai_output, :genai_summary, :internal_notes, :user_id,
                                  :kid_id, :cover_image, :additional_images, :active, :score)
      # : []
      # note on []: https://github.com/rails/rails/issues/35072
      # https://github.com/rails/rails/issues/35072
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def render_story_title(story)
    if begin
      story.title.size
    rescue StandardError
      0
    end > 3
      story.title
    else
      '🚧 Not available yet2 🚧'
    end
  end

  def render_story(story)
    if story.is_a?(Story)
      input_size = begin
        story.genai_input.size
      rescue StandardError
        0
      end
      output_size = begin
        story.genai_output.size
      rescue StandardError
        0
      end
      three_buttons = ''
      three_buttons << link_to("✅#{story.id}", story)
      three_buttons << link_to('📝', edit_story_path(story))
      three_buttons << (button_to '💣', story, method: :delete)
      title = render_story_title(story)
      arr = [
        three_buttons.html_safe,
        link_to(story.kid.nick, story.kid),
        link_to(title, story),
        begin
          image_tag(story.cover_image, height: 100)
        rescue StandardError
          ''
        end

      ]
      ret = arr.map { |el| "<td>#{el}</td>" }.join("\n")
    else
      arr = [
        'opts',
        'Kid',
        'Title',
        'cover_image',
        'I/O size'
      ]
      ret = arr.map { |el| "<th>#{el}</th>" }.join("\n")
    end

    ret.html_safe
  end

  def render_story_fix_button(story)
    '(fixme)' #"span class btn TODO Button fix now and fix later"
  end
end

app/views/stories/_beautified_story.html.erb
<h2><%= StoryParagraph.emoji %><%= @story.title %> 👷‍♀️ Beauty (v3)</h2>

[This needs a mutation in story DB Schema]

<h3>Obsolete StoryRebuild - Beautified(<%= @story_paragraphs.first.flag rescue "💔" %>)</h3>

<%= render 'stories/obsolete_pointer' %>


<div class='beautified_story' >
  <% @story_paragraphs.each_with_index do |p, ix|
    left_style = "float: left; margin: 0px 15px 15px 0px;"
    right_style = "float: right; margin: 0px 15px 15px 0px;"
    alternative_style = "float: #{ix %2 == 0 ? :left : :right}; margin: 0px 15px 15px 0px;"
  %>
    <div class='beautified_paragraph wrapper'  >
      <p  class="beautified-paragraph demo-2 subhead" >
        <%= render_image_if_attached(p.p_image1, verbose: false , style: alternative_style, width: 200) %>
        <%= raw( p.translated_text.gsub(/\*\*(A.* [1-5])\*\*/) { "<span class='act15' ><b><u>#{Regexp.last_match(1)}</u></b></span><br/><br/>" }.gsub('**','') )%>
      <%#= p.original_text %>
        <%= p.flag %>
        </p>
        <br style="clear:both" />

    </div>
  <% end if @story_paragraphs %>
</div>

app/views/stories/_bootstrap_index_card.html.erb
<% if story.is_a? Story %>
<%
  title = render_story_title(story)
  image = story.cover_image.attached? ?
    image_tag(story.cover_image, class: "card-img-top" ) :
    '(no img)'
  input_size = story.genai_input.size rescue 0
  output_size =  story.genai_output.size rescue 0
  my_translated_stories= story.translated_stories
  num_translated_stories = my_translated_stories.size

%>
<div class="card" style="width: 18rem;">
    <div class="card-footer small">
        <h5 class="card-title"><%= link_to(title, story) %></h5>
    </div>
    <%= image %>
    <div class="card-body">
        <p class="card-text">
            <%= link_to(story.kid.nick, story.kid) %>,
            <i><%= distance_of_time_in_words(story.updated_at, Time.now) %> ago</i>
        </p>
        <p class='small' ><%= story.genai_output_excerpt %></p>
    <div class="btn-group" role="group" aria-label="Basic outlined example">
    <% if num_translated_stories == 0 %>
      <!-- no translation! -->
      <%= link_to "❌ Translate to #{story.kid.flag}" , "/stories/#{story.id}?translate_to=#{story.kid.language}", class: "btn btn-primary" %>
    <% else  %>
      <!-- some translations available! -->
      <% story.translated_stories.each do |ts| %>
        <% if  ts.cached_completion > 99 %>
          <%= link_to "🎠💯 #{ts.flag}",translated_story_path(ts) + "?style=carousel", :class => "btn  btn-outline-primary" %>
        <% end %>
      <% end %>
    <% end %>

    </div>
    </div>
    <div class="card-footer small">
        id=#<%= story.id %>
        <%= link_to("✅ Show", story) %>
        <%= link_to('📝 Edit', edit_story_path(story))%>
        <kbd><%= story.score %></kbd>

        <!-- No 💣 -->
        <!-- No IO either, too confusing
        I/O: <%#=   "#{input_size} / #{output_size}" %>
        -->
    </div>
</div>
<% else %>
    not a story :/
<% end %>

app/views/stories/_button_translate_to_xx.html.erb
Note: currently this is NOT utilized.

  ❌ Missing: <%= link_to "Translate to #{waving_flag language}", # https://stackoverflow.com/questions/15410895/rails-ruby-prepopulate-form-with-data-passed-from-another-page
    new_translated_story_path({
      :story_id => @story.id,
      :story => @story,
      :language => language,
      :internal_notes => "#{@story.title} -- Created from _story.html AppVersion=#{APP_VERSION}",
      :name => "#{waving_flag(language)} Translation of: #{@story.title}",
      #'translated_story[name]' => 'nome 1',
      #'translated_story[name]'.to_sym => 'nome2',
      },
      #:class => "debug btn btn-primary"
    )#, method: :post
    %>

app/views/stories/_obsolete_pointer.html.erb
<p class='debug' >
This page is OBSOLETE. You should look at TranslatedStory instead..
, # story_id => 2013

@story = Story.find(params[:id]) <br/>
- Story: <%= @story %> <br/>
- id: <%= params[:id] %> <br/>
</p>

<h4>[New 🌍] TranslatedStories for story # <%=params[:id] %></h4>

<p class='debug' >
    <% TranslatedStory.where(story_id: params[:id]).each do |ts| %>
    🌍 <%= link_to ts,ts %> <br/>
    <% end %>
</p>

app/views/stories/_story_card.html.erb
<!-- TODO learn and use Flexbox!!
https://stackoverflow.com/questions/52397086/align-multiple-css-cards-in-html
-> https://css-tricks.com/snippets/css/a-guide-to-flexbox/   WOW!

to have 3 cards justaposed I used this:
https://stackoverflow.com/questions/2156712/how-to-float-3-divs-side-by-side-using-css
-->
<% cards_per_row ||= 3 %>
  <div class="card" style="float: left; width: 32%;">
      <p><%= story.genai_output.first(250) %>..
      <%= link_to 'more..',story %>
      [  <%= link_to '💄 Beauty', "/story_rebuilt/#{story.id}?beautfied=true" %>]
      </p>
      <div class="part2">
        <%= image_tag(story.cover_image, alt: "avatar", style: "width:100%") if story.cover_image.attached? %>
        <h4><%= story.cleaned_up_title %></h4>
        <i><%= distance_of_time_in_words(story.updated_at, Time.now) %> ago</i>
      </div>
  </div>

app/views/stories/_working_story.html.erb
<h2>OBSOLETE <%= StoryParagraph.emoji %><%= @story.title %> 👷‍♀️ Rebuilt (v2)</h2>

If the translated text is empty, reload or call from rails c this command:

TODO(ricc): use HotWire to auto update these as they're populated.

<table border="0" >
    <%= render_working_story_paragraph(nil) %>
  <% @story_paragraphs.each do |p| %>
    <%= render_working_story_paragraph(p) %>
  <% end %>
</table>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Show this story", @story %> |
  <%= link_to "Back to stories", stories_path %>
</div>

app/views/stories/index.html.erb
<% @stories_per_row ||= 4 %>
<h1><%= Story.emoji %> Stories </h1>

<%= link_to "New #{Story.emoji} story", new_story_path %>
<!-- pagination -->
<%= render 'layouts/pagination_tab', locals: {entity: 'stories' } %>
<div class="container text-center">
  <div class="row">
    <%@stories.each_with_index do |x, ix| %>
      <div class="col">
        <%= render 'stories/bootstrap_index_card', story: x, index: ix %>
      </div>
      <% if ix % @stories_per_row == @stories_per_row-1 %>
      <div class="row">
      <% end %>
    <% end %>
  </div>
</div>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Back to stories", stories_path %>
</div>

app/views/stories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @story %>

<!-- BootStrap is really awesome: https://getbootstrap.com/docs/5.3/components/button-group/ -->
<div class="btn-group" role="group" aria-label="Basic example">
  <div class="btn-group-sm me-2" role="group" aria-label="First group">
    <%= link_to "🔙 Back", stories_path, class: "btn btn-outline-success"  %>
    <%= link_to "📝 Edit", edit_story_path(@story),  class: "btn btn-outline-primary" %>
    <%= button_to "💣 Destroy! 💣", @story, method: :delete,  class: "btn btn-danger" %>
  </div>
  <div class="btn-group-sm me-2" role="group" aria-label="Second group">
    <button type="button" class="btn btn-secondary">🚧 New alternative story</button>
    <button type="button" class="btn btn-secondary">🚧 New Sequel</button>
  </div>
  <%#= button_to "🚧 New alternative story", @story, method: :genai_alternative %>
  <%#= button_to "🚧 New Sequel", @story, method: :genai_sequel %>
 <%#= link_to "🚧 Translate to Italian", "/story_rebuilt/#{@story.id}?translate_to=it", method: :post %>
 <%#= button_to "🚧 Translate to Japanese", @story, method: :genai_sequel %>
</div>

<hr/>
<%= render 'stories/story-old', locals: {story: @story } unless prod? %>

app/views/stories/show_rebuilt.html.erb
<p style="color: green"><%= notice %></p>

      <%= image_tag(@story.cover_image,  style: "float:right;height:200px;") if @story.cover_image.attached? %>
   See <%= link_to '📚 Normal story', "/stories/#{@story.id}" %>

<% if @translate_to &&  @story_paragraphs.size == 0 %>
  <h2> @translate_to activated! for ''<%= @translate_to %>''  </h2>
  <p>@story_paragraphs.size = <%= @story_paragraphs.size %></p>
  <p>Please wait a minute while I conjure the powers of AI...

  <% if params[:now] == 'true' %>
    IMMEDIATE execution...
    <%  @story.generate_paragraphs(lang: @translate_to) %>
  <%  else %>
    Delayed execution... use  (<%= link_to('now=true', "#{request.fullpath.to_s}&now=true") %> ) to make it immediate
  <%  @story.delay(queue: 'story::view_generate_paragraphs').generate_paragraphs(lang: @translate_to) %>
  <%  end %>
  ... and since Im a crappy FE developer, please hit reload in a while :P</p>
<% end %>

<% if params[:beautfied] == 'true' %>
   See <%= link_to '👨‍🚒 Normal RebuiltStory', "/story_rebuilt/#{@story.id}?beautfied=false" %>
  <%= render 'stories/beautified_story' %>
<% else  %>
   See <%= link_to '💄 Beautified RebuiltStory', "/story_rebuilt/#{@story.id}?beautfied=true" %>
  <%= render 'stories/working_story' %>
<% end  %>

<div>
  <%= link_to "📝 Edit this story", edit_story_path(@story) %> |
  <%= link_to "🔙 Back to stories", stories_path %>
  <%= button_to "🚧 New Sequel", @story, method: :genai_sequel %>

  <%= button_to "💣 Destroy this story", @story, method: :delete %>
  <%= button_to "🚧 New alternative story", @story, method: :genai_alternative %>
</div>